# REV: 1.0 | 2025-09-25 | Hash: d2cbdb00 | Parça: 1/1
repos:
  - repo: local
    hooks:
      - id: otokodlama-blockcheck
        name: "Blok Doğrulama & İndeks"
        entry: python tools/blockcheck.py
        language: system
        pass_filenames: false

      - id: otokodlama-guardrail
        name: "Guardrail Kontrolü (base.html & base.css)"
        entry: python tools/guardrail_check.py
        language: system
        files: '^(templates/base\.html|static/css/base\.css)$'
        pass_filenames: false

      - id: otokodlama-revstamp
        name: "Revizyon Damgası"
        entry: python tools/revstamp.py
        language: system
        exclude: '^(pipeline\.config\.json|targets/.*|_otokodlama/.*)$'
        pass_filenames: false
        stages: [manual]