# REV: 1.0 | 2025-09-25 | Hash: 1cbb210e | Parça: 1/1
# Generated by Django 5.2.6 on 2025-09-03 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('discipline', models.CharField(choices=[('ELEC', 'Elektrik'), ('MECH', 'Mekanik'), ('PNEU', 'Pnömatik')], default='MECH', max_length=4)),
                ('criticality', models.PositiveSmallIntegerField(default=3, help_text='1=En kritik, 5=En az kritik')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_calibration', models.DateField(blank=True, null=True)),
                ('next_calibration', models.DateField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=120)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Günlük'), ('WEEKLY', 'Haftalık'), ('MONTHLY', 'Aylık'), ('QTR', '3 Aylık'), ('YEARLY', 'Yıllık')], default='MONTHLY', max_length=10)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('PLN', 'Planlı'), ('PRD', 'Kestirimci'), ('BRK', 'Arızi')], default='PLN', max_length=3)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('technician', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planlandı'), ('COMPLETED', 'Tamamlandı'), ('OVERDUE', 'Gecikmiş')], default='SCHEDULED', max_length=12)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipment')),
            ],
            options={
                'ordering': ['-due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_critical', models.BooleanField(default=False)),
                ('stock_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.equipment')),
            ],
        ),
    ]
