# Generated by Django 5.2.6 on 2025-09-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_calibration_asset_migrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationrecord',
            options={'ordering': ['-next_calibration', '-id']},
        ),
        migrations.AddField(
            model_name='calibrationrecord',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=120, verbose_name='Sertifika No'),
        ),
        migrations.AddField(
            model_name='calibrationrecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='last_calibration',
            field=models.DateField(blank=True, null=True, verbose_name='Son Kalibrasyon'),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='next_calibration',
            field=models.DateField(blank=True, null=True, verbose_name='Sonraki Kalibrasyon'),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='result',
            field=models.CharField(blank=True, max_length=120, verbose_name='Sonuç'),
        ),
    ]
