# REV: 1.0 | 2025-09-24 | Hash: 62566716 | Parça: 1/1
# Generated by Django 5.2.6 on 2025-09-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_calibrationrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Üretici Firma'),
        ),
        migrations.AlterField(
            model_name='maintenancechecklistitem',
            name='frequency',
            field=models.CharField(choices=[('AYLIK', 'Aylık'), ('3AYLIK', '3 Aylık'), ('6AYLIK', '6 Aylık'), ('YILLIK', 'Yıllık')], default='AYLIK', max_length=10),
        ),
    ]
