# Generated by Django 5.2.6 on 2025-09-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_equipment_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Üretici Firma'),
        ),
        migrations.AlterField(
            model_name='maintenancechecklistitem',
            name='frequency',
            field=models.CharField(choices=[('AYLIK', 'Aylık'), ('3AYLIK', '3 Aylık'), ('6AYLIK', '6 Aylık'), ('YILLIK', 'Yıllık')], default='AYLIK', max_length=10, verbose_name='Bakım / Kontrol Periyodu'),
        ),
        migrations.AlterField(
            model_name='maintenancechecklistitem',
            name='is_mandatory',
            field=models.BooleanField(default=True, verbose_name='Zorunlu'),
        ),
        migrations.AlterField(
            model_name='maintenancechecklistitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Bakım / Kontrol Tanımı'),
        ),
    ]
