# REV: 1.0 | 2025-09-25 | Hash: 8e075c04 | Parça: 1/1
# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0005_alter_equipment_manufacturer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationrecord",
            name="total_deviation",
            field=models.DecimalField(
                verbose_name="Toplam Sapma",
                max_digits=10,
                decimal_places=4,
                null=True,
                blank=True,
            ),
        ),
    ]
