# REV: 1.0 | 2025-09-25 | Hash: 6e90ef5c | Parça: 1/1
# Generated by Django 5.2.6 on 2025-09-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_add_total_deviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Üretici Firma'),
        ),
        migrations.AlterField(
            model_name='maintenancechecklistitem',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Günlük'), ('WEEKLY', 'Haftalık'), ('MONTHLY', 'Aylık'), ('QTR', '3 Aylık'), ('YEARLY', 'Yıllık')], default='MONTHLY', max_length=10),
        ),
        migrations.AlterField(
            model_name='maintenancechecklistitem',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='maintenancechecklistitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
