# Generated by Django 5.2.6 on 2025-10-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_equipment_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Departman Adı')),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
            },
        ),
        migrations.RemoveField(
            model_name='calibrationrecord',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='maintenancechecklistitem',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='maintenanceorder',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='equipment',
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'Ekipman', 'verbose_name_plural': 'Ekipmanlar'},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='area',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='code',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='criticality',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='equipment',
            name='inventory_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Envanter Kodu'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(default='depo', max_length=100, verbose_name='Konum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Satın Alma Tarihi'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(default='tek', max_length=100, unique=True, verbose_name='Seri Numarası'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ekipman Adı'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.department', verbose_name='Departman'),
        ),
        migrations.DeleteModel(
            name='CalibrationAsset',
        ),
        migrations.DeleteModel(
            name='CalibrationRecord',
        ),
        migrations.DeleteModel(
            name='MaintenanceChecklistItem',
        ),
        migrations.DeleteModel(
            name='MaintenanceOrder',
        ),
        migrations.DeleteModel(
            name='SparePart',
        ),
    ]
