# Generated by Django 5.2.6 on 2025-10-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_department_remove_calibrationrecord_asset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='inventory_code',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_date',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Departman AdÃƒÆ’Ã¢â‚¬Â\x9eÃƒâ€šÃ‚Â±'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ekipman AdÃƒÆ’Ã¢â‚¬Â\x9eÃƒâ€šÃ‚Â±'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
