name: Auto Approve UI PR
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

jobs:
  approve:
    if: contains(toJson(github.event.pull_request.labels), '"ui-tests"')
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve when label present
        uses: peter-evans/approve-pull-request@v6
        with:
          token: ${{ secrets.OZKAN_PAT }}
          pull-request-number: ${{ github.event.pull_request.number }}
          message: Auto-approve: UI pipeline green.
