name: E2E – Django + Playwright
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Install Playwright browsers + OS deps
        run: npx playwright install --with-deps

      - name: Migrate DB & seed admin
        env:
          DJANGO_SETTINGS_MODULE: core.settings_maintenance
        run: |
          python manage.py migrate --noinput
          python - <<'PY'
          import os, django
          os.environ.setdefault("DJANGO_SETTINGS_MODULE","core.settings_maintenance")
          django.setup()
          from django.contrib.auth import get_user_model
          U = get_user_model()
          u, _ = U.objects.get_or_create(
              username="admin",
              defaults={"email":"admin@example.com","is_staff":True,"is_superuser":True}
          )
          u.is_staff = True; u.is_superuser = True
          u.set_password("admin123!"); u.save()
          print("Admin OK:", u.username)
          PY

      - name: Start Django dev server
        env:
          DJANGO_SETTINGS_MODULE: core.settings_maintenance
          ALLOW_EQUIPMENT_ADD: "1"
        run: |
          python manage.py runserver 127.0.0.1:8010 --noreload &
          for i in {1..60}; do
            curl -sSf http://127.0.0.1:8010/admin/ >/dev/null && break
            sleep 1
          done

      - name: Run Playwright tests (headless)
        env:
          BASE_URL: http://127.0.0.1:8010
          E2E_USER: admin
          E2E_PASS: admin123!
        run: npx playwright test --reporter=html

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload traces & screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 7