name: E2E – Django + Playwright (Windows)
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  e2e-win:
    runs-on: windows-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if (Test-Path package-lock.json) { npm ci } else { npm i }
          npx playwright install

      - name: Migrate & seed admin
        shell: pwsh
        env:
          DJANGO_SETTINGS_MODULE: core.settings_maintenance
        run: |
          python manage.py migrate --noinput
          python - << 'PY'
          import os, django
          os.environ.setdefault("DJANGO_SETTINGS_MODULE","core.settings_maintenance")
          django.setup()
          from django.contrib.auth import get_user_model
          U = get_user_model()
          u, _ = U.objects.get_or_create(username="admin",
              defaults={"email":"admin@example.com","is_staff":True,"is_superuser":True})
          u.is_staff=True; u.is_superuser=True; u.set_password("admin123!"); u.save()
          print("Admin OK:", u.username)
          PY

      - name: Start runserver + healthcheck
        shell: pwsh
        env:
          DJANGO_SETTINGS_MODULE: core.settings_maintenance
          ALLOW_EQUIPMENT_ADD: "1"
        run: |
          Start-Process -FilePath python -ArgumentList @('manage.py','runserver','127.0.0.1:8010','--noreload')
          $ok=$false; 1..60 | % {
            try { iwr http://127.0.0.1:8010/admin/ -UseBasicParsing -TimeoutSec 3 | Out-Null; $ok=$true; break } catch {}
            Start-Sleep -Seconds 1
          }
          if (-not $ok) { throw "Server healthcheck failed" }

      - name: Run Playwright (headless)
        shell: pwsh
        env:
          BASE_URL: http://127.0.0.1:8010
          E2E_USER: admin
          E2E_PASS: admin123!
        run: npx playwright test --reporter=html

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results
          retention-days: 7