name: E2E (reusable)

on:
  workflow_call:
    inputs:
      base_url:
        type: string
        required: true
    secrets: {}

permissions:
  contents: read
  actions: write
  checks: write
  id-token: write

jobs:
  e2e:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") { pip install -r requirements.txt }

      - name: Install Node deps
        run: |
          if (Test-Path "package-lock.json") { npm ci } elseif (Test-Path "package.json") { npm i }

      - name: Export env
        shell: pwsh
        run: |
          "BASE_URL=${{ inputs.base_url }}" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "ADMIN_USER=admin"               | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "ADMIN_PASS=admin"               | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Start Django (background)
        shell: pwsh
        env:
          DJANGO_SETTINGS_MODULE: "core.settings_maintenance"
        run: |
          if (Test-Path "manage.py") {
            Start-Process -FilePath "python" -ArgumentList "manage.py","runserver","127.0.0.1:8010" -WindowStyle Hidden
            $deadline = [DateTime]::UtcNow.AddSeconds(60)
            while ([DateTime]::UtcNow -lt $deadline) {
              try {
                $c = New-Object Net.Sockets.TcpClient
                $iar = $c.BeginConnect("127.0.0.1",8010,$null,$null)
                $ok = $iar.AsyncWaitHandle.WaitOne(1000)
                if ($ok -and $c.Connected) { $c.Close(); break }
                $c.Close()
              } catch {}
              Start-Sleep -Milliseconds 500
            }
          }

      - name: Tolerant smoke (302 OK kabul)
        shell: pwsh
        run: |
          try {
            $r = Invoke-WebRequest -Uri "${{ inputs.base_url }}" -MaximumRedirection 0 -ErrorAction Stop
            "SMOKE HTTP $($r.StatusCode)" | Write-Host
          } catch {
            $code = [int]$_.Exception.Response.StatusCode
            if ($code -in 301,302,303,307,308) {
              "SMOKE Redirect $code kabul" | Write-Host
            } else {
              throw
            }
          }

      - name: Build tasks (ensure tasks.json)
        shell: pwsh
        run: |
          if (Test-Path "scripts/build-tasks.js") {
            node scripts/build-tasks.js
          } elseif (Test-Path "tools/tasks_from_csv.ps1") {
            powershell -File tools/tasks_from_csv.ps1 -Csv "tasks_template.csv" -OutJson "build/tasks.json"
            Copy-Item build/tasks.json tasks.json -Force
          } else {
            New-Item -Force -ItemType Directory -Path build | Out-Null
            $json = @"
{ "meta": {"generatedAt":"$(Get-Date -Format s)","source":"fallback"},
  "jobs":[{"id":"ADMIN_SMOKE","title":"Admin login smoke",
           "steps":[{"action":"goto","url":"/admin/login/"}]}] }
"@
            $json | Set-Content tasks.json -Encoding UTF8
            Copy-Item tasks.json build/tasks.json -Force
          }

      - name: Verify tasks.json exists
        shell: pwsh
        run: |
          Write-Host "== ls =="
          Get-ChildItem -Recurse -File tasks.json, build/tasks.json -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName }
          if (!(Test-Path "tasks.json") -and !(Test-Path "build/tasks.json")) {
            Write-Error "tasks.json HÂLÂ yok!"
            exit 1
          } else {
            Write-Host "tasks.json mevcut ✅"
            if (Test-Path "tasks.json") { Get-Content tasks.json | Select-Object -First 30 }
          }

      - name: Run Playwright tests
        run: |
          npx playwright install --with-deps
          npx playwright test --reporter line,html
          # İsterseniz yalnız smoke senaryosunu koşturmak için:
          # npx playwright test tests/tasks.spec.js --reporter line,html

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: warn