name: E2E Dispatch

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: Base URL
        required: true
        type: string
        default: "http://127.0.0.1:8010"

jobs:
  call-e2e:
    uses: koordinator-maker/bakim_kalibrasyon_rep/.github/workflows/e2e.yml@ci/add-e2e-dispatcher
    with:
      base_url: ${{ inputs.base_url }}