name: pipeline
on: [push, pull_request]
jobs:
  run:
    runs-on: windows-latest
    steps:
      - name: Django migrate + seed admin
        shell: pwsh
        env:
          DJANGO_SETTINGS_MODULE: "core.settings_maintenance"
        run: |
          if (Test-Path "manage.py") {
            python -m pip install --upgrade pip
            if (Test-Path "requirements.txt") { pip install -r requirements.txt }
            python manage.py migrate --settings=core.settings_maintenance
            $u = "${env:ADMIN_USER}"; if (-not $u) { $u="admin" }
            $p = "${env:ADMIN_PASS}"; if (-not $p) { $p="Admin!2345" }
            python manage.py shell --settings=core.settings_maintenance -c "from django.contrib.auth import get_user_model as G; U=G(); u,created=U.objects.get_or_create(username='$u', defaults={'email':'admin@example.com','is_staff':True,'is_superuser':True}); u.is_staff=True; u.is_superuser=True; u.set_password('$p'); u.save(); print('created' if created else 'updated')"
          }      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install playwright
          python -m playwright install chromium
      - name: Serve & Pipeline
        shell: pwsh
        run: powershell -ExecutionPolicy Bypass -File .\tools\serve_then_pipeline.ps1 -BindHost 127.0.0.1 -Port 8000
      - name: Upload screenshots (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: screens
          path: targets/screens/*.png
