name: PR Maintenance
on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled, ready_for_review]
permissions:
  contents: read
  pull-requests: write
jobs:
  maintain:
    runs-on: ubuntu-latest
    steps:
      - name: Setup gh CLI
        uses: cli/gh-actions@v2
      - name: Health check + no-op
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh --version || true
          echo "PR Maintenance OK"