name: PR Maintenance (auto-approve & merge)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  maintain:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve & enable auto-merge (tolerant)
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        shell: bash
        run: |
          pr=${{ github.event.pull_request.number }}
          slug=${{ github.repository }}

          # (Opsiyonel) PR branch'ini güncelle - hata verse de devam
          sha=$(gh pr view "$pr" --json headRefOid --jq .headRefOid 2>/dev/null || true)
          if [ -n "$sha" ]; then
            gh api -X PUT "repos/$slug/pulls/$pr/update-branch" \
              -f expected_head_sha="$sha" \
              -H "Accept: application/vnd.github+json" || true
          fi

          # Onay ver; zaten onaylıysa sorun etme
          gh pr review "$pr" --approve || true

          # Auto-merge'i aç; şartlar hazır değilse hata verse de job YEŞİL kalsın
          gh pr merge "$pr" --squash --auto || true

          echo "PR Maintenance completed (tolerant mode)."