name: PR Maintenance (auto-approve & merge)
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
permissions:
  contents: write
  pull-requests: write
jobs:
  maintain:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve & enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        shell: bash
        run: |
          pr=${{ github.event.pull_request.number }}
          # (İsteğe bağlı) PR branch’ini main ile güncelle
          slug=${{ github.repository }}
          sha=$(gh pr view "$pr" --json headRefOid --jq .headRefOid)
          gh api -X PUT "repos/$slug/pulls/$pr/update-branch" \
            -F expected_head_sha="$sha" \
            -H "Accept: application/vnd.github+json" || true
          # Onay + auto-merge
          gh pr review "$pr" --approve || true
          gh pr merge  "$pr" --squash --auto