name: PR Maintenance (auto-approve & merge)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  maintain:
    runs-on: ubuntu-latest
    steps:
      - name: Who am I (bot)
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        shell: bash
        run: |
          echo "BOT_LOGIN=$(gh api user -q .login)"
          echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}"

      - name: Auto-approve & enable auto-merge (tolerant)
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        shell: bash
        run: |
          set -e
          pr=${{ github.event.pull_request.number }}
          slug=${{ github.repository }}

          # (Opsiyonel) base ile güncelle - hata verse de akışı bozma
          sha=$(gh pr view "$pr" --json headRefOid --jq .headRefOid 2>/dev/null || true)
          if [ -n "$sha" ]; then
            gh api -X PUT "repos/$slug/pulls/$pr/update-branch" \
              -f expected_head_sha="$sha" \
              -H "Accept: application/vnd.github+json" || true
          fi

          # Onayla (gerekliyse); "own PR" veya gerek yoksa sorun etme
          gh pr review "$pr" --approve || true

          # Auto-merge aç (şartlar hazır değilse hata verse de YEŞİL kalsın)
          gh pr merge "$pr" --squash --auto || true

          echo "PR Maintenance done."