name: UI Validate (DOM)

on:
  pull_request:
    paths:
      - "ops/ui_validate.csv"
      - ".github/workflows/ui-validate.yml"
  workflow_dispatch: {}

permissions:
  contents: read
  actions: write

jobs:
  ui-validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        if: ${{ hashFiles('requirements.txt') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UI validations (CSV)
        if: ${{ hashFiles('ops/ui_validate.csv') != '' }}
        shell: pwsh
        continue-on-error: true
        run: |
          New-Item -Force -ItemType Directory -Path _otokodlama/out | Out-Null
          New-Item -Force -ItemType Directory -Path _otokodlama/alerts | Out-Null
          # Örnek/placeholder doğrulama – gerçek komutunuzu buraya koyun:
          # python tools/ui_validate.py -i ops/ui_validate.csv -o _otokodlama/out/ui_validate.json
          '[{"status":"ok","checks":0}]' | Set-Content _otokodlama/out/ui_validate.json -Encoding UTF8

      - name: Upload JSON results
        if: ${{ hashFiles('_otokodlama/out/*.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: ui-validate-json
          path: _otokodlama/out/*.json
          if-no-files-found: warn

      - name: Upload alerts (screenshots & logs)
        if: ${{ hashFiles('_otokodlama/alerts/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: ui-validate-alerts
          path: _otokodlama/alerts/**
          if-no-files-found: warn